import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { QueryProvider } from "@/lib/query-provider";
import VerificationPrompt from "./dashboard/_components/verification-prompt";
import { Suspense } from "react";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <QueryProvider>
      <html lang="en">
        <body className={`${inter.className} h-screen w-screen relative overflow-x-hidden`}>
          <Suspense>
            <VerificationPrompt />
            {children}
          </Suspense>
          <Toaster />
        </body>
      </html>
    </QueryProvider>
  );
}
